all:
	gcc exercicio1a.c -o exercicio1a
	./exercicio1a
	gcc exercicio1b.c -o exercicio1b
	./exercicio1b
	gcc exercicio1c.c -o exercicio1c
	./exercicio1c
	gcc exercicio1d.c -o exercicio1d
	./exercicio1d
	gcc exercicio2a.c -o exercicio2a
	./exercicio2a
	gcc exercicio2b.c -o exercicio2b
	./exercicio2b
	gcc exercicio2c.c -o exercicio2c
	./exercicio2c
	rm exercicio1a exercicio1b exercicio1c exercicio1d exercicio2a exercicio2b exercicio2c